
export const tempDocs = [
  {
      id: 1,
      requestTypeId: 1,
      counterPartyCode: "421455959",
      counterPartyName: "ТОВ КУА 'СИСТЕМА ПЛЮС'",
      documentDate: "2019-04-15",
      receiveDate: "2019-04-15",
      inNum: null,
      outNum: null,
      inDate: null,
      outDate: null,
      externalGuid: null,
      requestId: 1,
      recordDate: "2017-08-17",
      issuerCode: "12042041",
      issuerEdrici: null,
      issuerName: "АКЦІОНЕРНЕ ТОВАРИСТВО 'ЗАКРИТИЙ НЕДИВЕРСИФІКОВАНИЙ ВЕНЧУРНИЙ КОРПОРАТИВНИЙ ІНВЕСТИЦІЙНИЙ ФОНД КОВЕНАНТ'",
      isin: "UA4000072349",
      fitext: "АТ ЗНВКІФ КОВЕНАНТ",
      paperType_1: null,
      paperType_2: null,
      paperType_3: null,
      digitType_1: null,
      digitType_2: null,
      digitType_3: null,
      withBank: 1,
      withTemp: 1,
      isTerm: 1,
      reasonCode: "ReasonCode",
      reasonText: "ReasonText",
      code: "Accepted"
  },
  {
    id: 2,
    requestTypeId: 1,
    counterPartyCode: "421455959",
    counterPartyName: "ТОВ КУА 'СИСТЕМА ПЛЮС'",
    documentDate: "2019-04-15",
    receiveDate: "2019-04-15",
    inNum: null,
    outNum: null,
    inDate: null,
    outDate: null,
    externalGuid: null,
    requestId: 1,
    recordDate: "2017-08-17",
    issuerCode: "12042041",
    issuerEdrici: null,
    issuerName: "АКЦІОНЕРНЕ ТОВАРИСТВО 'ЗАКРИТИЙ НЕДИВЕРСИФІКОВАНИЙ ВЕНЧУРНИЙ КОРПОРАТИВНИЙ ІНВЕСТИЦІЙНИЙ ФОНД КОВЕНАНТ'",
    isin: "UA4000072349",
    fitext: "АТ ЗНВКІФ КОВЕНАНТ",
    paperType_1: null,
    paperType_2: null,
    paperType_3: null,
    digitType_1: null,
    digitType_2: null,
    digitType_3: null,
    withBank: 1,
    withTemp: 1,
    isTerm: 1,
    reasonCode: "ReasonCode",
    reasonText: "ReasonText",
    code: "Accepted"
},
{
  id: 3,
  requestTypeId: 1,
  counterPartyCode: "421455959",
  counterPartyName: "ТОВ КУА 'СИСТЕМА ПЛЮС'",
  documentDate: "2019-04-15",
  receiveDate: "2019-04-15",
  inNum: null,
  outNum: null,
  inDate: null,
  outDate: null,
  externalGuid: null,
  requestId: 1,
  recordDate: "2017-08-17",
  issuerCode: "12042041",
  issuerEdrici: null,
  issuerName: "АКЦІОНЕРНЕ ТОВАРИСТВО 'ЗАКРИТИЙ НЕДИВЕРСИФІКОВАНИЙ ВЕНЧУРНИЙ КОРПОРАТИВНИЙ ІНВЕСТИЦІЙНИЙ ФОНД КОВЕНАНТ'",
  isin: "UA4000072349",
  fitext: "АТ ЗНВКІФ КОВЕНАНТ",
  paperType_1: null,
  paperType_2: null,
  paperType_3: null,
  digitType_1: null,
  digitType_2: null,
  digitType_3: null,
  withBank: 1,
  withTemp: 1,
  isTerm: 1,
  reasonCode: "ReasonCode",
  reasonText: "ReasonText",
  code: "Accepted"
},
  
];